# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 14:45
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0004_auto_20150623_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='info',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), blank=True, null=True, size=None),
        ),
    ]
