# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 12:32
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0005_auto_20170421_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='options',
            field=jsonfield.fields.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='moduletype',
            name='schema',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
