# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0006_auto_20170606_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
