# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collectors', '0003_auto_20150730_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collector',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collectors', to='collectors.CollectorType'),
        ),
    ]
