# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 12:32
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('collectors', '0004_auto_20170421_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collector',
            name='options',
            field=jsonfield.fields.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='collector',
            name='query',
            field=jsonfield.fields.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='collectortype',
            name='options_schema',
            field=jsonfield.fields.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='collectortype',
            name='query_schema',
            field=jsonfield.fields.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='provider',
            name='credentials_schema',
            field=jsonfield.fields.JSONField(blank=True, default=dict),
        ),
    ]
