import os
import json
import sys


def get_credentials_or_die():
    try:
        # This should be the json generated by clicking Create new Client ID
        # and selecting Service account in the google developer console.
        client_json = os.environ['GOOGLE_CREDENTIALS']
        credentials = json.loads(client_json)
        return credentials['client_email'], credentials['private_key']
    except KeyError:
        print("Please supply as an environment variable:")
        print("GOOGLE_CREDENTIALS")
        print("This should be the json generated by clicking "
              "Create new Client ID and selecting Service "
              "account in the google developer console.")
        sys.exit(1)
