# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 12:32
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('transforms', '0003_auto_20150707_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transform',
            name='options',
            field=jsonfield.fields.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='transform',
            name='query_parameters',
            field=jsonfield.fields.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='transformtype',
            name='schema',
            field=jsonfield.fields.JSONField(blank=True, default=dict),
        ),
    ]
